config/routes.rb
Rails.application.routes.draw do
  resources :twitts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "twitts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twitt.rb
class Twitt < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/twitts_controller.rb
class TwittsController < ApplicationController
  before_action :set_twitt, only: [:show, :edit, :update, :destroy]

  # GET /twitts
  # GET /twitts.json
  def index
    @twitts = Twitt.all
  end

  # GET /twitts/1
  # GET /twitts/1.json
  def show
  end

  # GET /twitts/new
  def new
    @twitt = Twitt.new
  end

  # GET /twitts/1/edit
  def edit
  end

  # POST /twitts
  # POST /twitts.json
  def create
    @twitt = Twitt.new(twitt_params)

    respond_to do |format|
      if @twitt.save
        format.html { redirect_to @twitt, notice: 'Twitt was successfully created.' }
        format.json { render :show, status: :created, location: @twitt }
      else
        format.html { render :new }
        format.json { render json: @twitt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twitts/1
  # PATCH/PUT /twitts/1.json
  def update
    respond_to do |format|
      if @twitt.update(twitt_params)
        format.html { redirect_to @twitt, notice: 'Twitt was successfully updated.' }
        format.json { render :show, status: :ok, location: @twitt }
      else
        format.html { render :edit }
        format.json { render json: @twitt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitts/1
  # DELETE /twitts/1.json
  def destroy
    @twitt.destroy
    respond_to do |format|
      format.html { redirect_to twitts_url, notice: 'Twitt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twitt
      @twitt = Twitt.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twitt_params
      params.require(:twitt).permit(:twitt)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitts_helper.rb
module TwittsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if flash[:notice]%>
    <div class="notification is-primary global -notification">
      <p class="notice"><%= notice%></p>
    </div>
    <%end%>

    <% if flash[:alert]%>
    <div class="notification is-danger global -notification">
    <p class="alert"><% alert %></p>
    </div>
    <%end%>
    <nav class="navbar is-info">
      <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do%>
      <h1 class="title is-5">Twitter</h1>

      <%end%>

      <div class="navbar-burger burger" data-target="navbarExample">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="field is-grouped">
          <p class="control">
            <%= link_to "New Twitt", new_twitt_path, class: "button is-info is-inverted" %>
        </p>
        <p class="control"> Sign Up </p>

      </div>
    </div>
  </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/twitts/_feed.html.erb
<div class="column is half">
	<article class="media box">
		<figure class="media-left">
			<p class="image is -64*64">
				<img src="https://bulma.io/images/placholder/64*64.png">
			</p>
		</figure>
		<div class="media-content">


		</div>
	</article>
</div>



<% @twitts.each do |t|%>
<div class="column is half">
	<article class="media box">
		<figure class="media-left">
			<p class="image is -64*64">
				<img src="https://bulma.io/images/placholder/64*64.png">
			</p>
		</figure>
	
</div>
<div class="media-content">
	<div class="content">
	<p><b>user name</b></p><br/>
	 <p><%= t.created_at %></p><br/>
	<p><strong><%= t.twitt%></strong></p>
	<div><strong><%=link_to t "twitt" %></strong></div>
	<div>
		<%#=link_to 'edit', edit_twitt_path(t), class :"level-item" do%>
		
	</div>
	<p><%= link_to 'Destroy' ,twitt_path(t), method: :delete, data: {confirm: "are you sure??"}%>
	</p>
</div>
</div>
</article>
</div>
	<%end%>

app/views/twitts/_form.html.erb
<%= form_with(model: twitt, local: true) do |form| %>
  <% if twitt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(twitt.errors.count, "error") %> prohibited this twitt from being saved:</h2>

      <ul>
        <% twitt.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :twitt %>
    <%= form.text_area :twitt %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/twitts/edit.html.erb
<h1>Editing Twitt</h1>

<%= render 'form', twitt: @twitt %>

<%= link_to 'Show', @twitt %> |
<%= link_to 'Back', twitts_path %>

app/views/twitts/index.html.erb
<section class="section">
  <div class="container">
    <div class ="columns">
  <%= render 'feed'%>    
  </div>
</section>

  <!-- <tbody>
    <% @twitts.each do |twitt| %>
      <tr>
        <td><%= twitt.twitt %></td>
        <td><%= link_to 'Show', twitt %></td>
        <td><%= link_to 'Edit', edit_twitt_path(twitt) %></td>
        <td><%= link_to 'Destroy', twitt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Twitt', new_twitt_path %>
 -->

app/views/twitts/new.html.erb
<h1>New Twitt</h1>

<%= render 'form', twitt: @twitt %>

<%= link_to 'Back', twitts_path %>

app/views/twitts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Twitt:</strong>
  <%= @twitt.twitt %>
</p>

<%= link_to 'Edit', edit_twitt_path(@twitt) %> |
<%= link_to 'Back', twitts_path %>